---
title: "Check References"
author: "Dean Calahan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---
```{r Setup, include=FALSE}
# note that the default working directory for 
knitr::opts_chunk$set(echo = TRUE)
library(Calahanlab)

# Working directory is the directory containing the .Rmd when running knitr
if(isTRUE(getOption('knitr.in.progress'))) {
    ref_dir <- "../../References/"
    pdf_dir <- "../../../../../../PDFs/"
    ms_fn <- "../../_EACCRPBT.scriv"
} else {
    ref_dir <- "References/"
    pdf_dir <- "../../../../PDFs/"
    ms_fn <- "_EACCRPBT.scriv"
}

refs_fn <- paste0(ref_dir, "_References.bdb.xml")
```
Refs exists?: `r file.exists(refs_fn)`  
PDFs exists?: `r dir.exists(pdf_dir)`  
Scriv exists?: `r file.exists(ms_fn)`
```{r Check, echo=FALSE}
refs_df <- RefDataFrame(refs_fn)
pdfs_needed <- LitNeeded(refs_df, pdf_dir, conv="title")
aliases_needed <- LitNeeded(refs_df, ref_dir, conv="title.al")
pdfs_extra <- LitExtra(refs_df, ref_dir, conv="title.al")
scr_todos <- GrepScriv(ms_fn, "\\[todo\\]")
dbl_spc <- GrepScriv(ms_fn, "  ")
scr_octothorpes <- GrepScriv(ms_fn, "\\[#\\]")
# word counts
# blank lines
# units
# directory tree
# file dates/times
# auto/code generated text
# spreadsheet
# "alias copy"
```
####Files needed in `r pdf_dir`   
```{r FilesNeeded, echo=FALSE}
pdfs_needed
```
####Files needed in `r ref_dir`   
```{r AliasesNeeded, echo=FALSE}
aliases_needed
```
####Extra files in `r ref_dir`   
```{r AliasesExtra, echo=FALSE}
pdfs_extra
```
####Entries whose DOI is NA
```{r DOI, echo=FALSE}
refs_df$title[is.na(refs_df$doi)]
```
####Entries whose URL is NA
```{r URL, echo=FALSE}
refs_df$title[is.na(refs_df$url)]
```
####Scrivenings with "todo"
```{r Todo, echo=FALSE}
scr_todos
```
